### ISSUE TITLE
MongoDB database growing during execution of workloada

### ISSUE THREAD

**Issue by jedimt** [brianfrankcooper/YCSB#1422]
New at this, so forgive my ignorance if I'm misconfiguring something. 

I've created a database as follows:
`./bin/ycsb load mongodb -s -P workloads/workloada -threads 32`

The workloada file has the following options (all default except for recordcount):
```
recordcount=30000000
operationcount=1000
workload=site.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0.5
updateproportion=0.5
scanproportion=0
insertproportion=0

requestdistribution=zipfian
```
I then run this script to test a stepping of threads:
```
for i in {1,2,4,8,16,32,64}
do
        ./bin/ycsb run mongodb -s -P workloads/workloada -p maxexecutiontime=300 -p operationcount=2147483647 -threads $i > $HOSTNAME-wla-run3-$i.txt
sleep 60
done
```

I noticed that my database increases in size during each run of the test.
mongors:PRIMARY> show dbs
admin    0.000GB
config   0.000GB
local   11.362GB
ycsb    35.266GB -> 
1 thread   41.127
2 thread   45.162
4 thread   57.344
8 thread   75.986
16 thread  85.827
32 thread  92.810
64 thread  97.399
128 thread 97.407

Based on what I read here, the 'workloada' test shouldn't increase the size of the database: https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads

Am I doing something wrong here?

**Comment by busbey** [comment]
Workload A  does 50% updates to existing keys. It picks the keys based on the assumption that the load phase was run with the same record count as it is given. Presuming that is a valid assumption then the logical size of the data set should not increase. If it is not valid then the behavior will depend on the datastore client; most of the datastores actually implement upsert rather than update.

In your case it looks like what you're seeing is not necessarily an increase in the logical data set size. It looks like it most likely is the backing datastore keeping a log of edits. What do record counts before and after the test run show?

**Comment by jedimt** [comment]
Hey Sean,
**#After a freshly populated load**
```
> use ycsb
switched to db ycsb
> show dbs
admin    0.000GB
config   0.000GB
local    0.000GB
ycsb    33.863GB
> db.stats()
{
        "db" : "ycsb",
        "collections" : 1,
        "views" : 0,
        "objects" : 30000000,
        "avgObjSize" : 1167.8795351333333,
        "dataSize" : 35036386054,
        "storageSize" : 34817404928,
        "numExtents" : 0,
        "indexes" : 1,
        "indexSize" : 1542963200,
        "scaleFactor" : 1,
        "fsUsedSize" : 56886333440,
        "fsTotalSize" : 1999023439872,
        "ok" : 1
}
> db.usertable.count()
30000000
```

**#After a test run**
```
> show dbs
admin    0.000GB
config   0.000GB
local    0.000GB
ycsb    86.864GB

> db.stats()
{
        "db" : "ycsb",
        "collections" : 1,
        "views" : 0,
        "objects" : 30000000,
        "avgObjSize" : 1167.8795351333333,
        "dataSize" : 35036386054,
        "storageSize" : 91903868928,
        "numExtents" : 0,
        "indexes" : 1,
        "indexSize" : 1366003712,
        "scaleFactor" : 1,
        "fsUsedSize" : 107574480896,
        "fsTotalSize" : 1999023439872,
        "ok" : 1
}
> db.usertable.count()
30000000
```
I don't have compression disabled, so not sure why the storageSize blows up with the number of records being constant. Just for kicks, here is my mongod.conf file.
```
[root@tme-sas0 YCSB]# cat /etc/mongod.conf
# Ansible managed

net:
  #bindIp: 127.0.0.1
  bindIp: localhost,<redacted>,127.0.0.1
  ipv6: false
  maxIncomingConnections: 51200
  port: 27017

processManagement:
  fork: true
  pidFilePath: /var/run/mongodb/mongod.pid

#replication:
#  oplogSizeMB: 1024
#  replSetName: mongors

security:
  authorization: disabled
  javascriptEnabled: false

storage:
  dbPath: /data/db
  directoryPerDB: true
  engine: wiredTiger
  journal:
    enabled: true
  wiredTiger:
    engineConfig:
      directoryForIndexes: false

systemLog:
  destination: file
  logAppend: true
  logRotate: rename
  path: /var/log/mongodb/mongod.log

operationProfiling:
  slowOpThresholdMs: 100
  mode: off

cloud:
  monitoring:
    free:
      state: runtime
```
